ALTER TABLE auditoria_logs
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;



-- =========================================================
-- 1) Função genérica de auditoria
-- =========================================================
CREATE OR REPLACE FUNCTION audit_generic() RETURNS trigger AS $$
DECLARE
    v_usuario_id bigint;
    v_ip         text;
    v_recurso    text := TG_TABLE_SCHEMA || '.' || TG_TABLE_NAME;
    v_detalhes   text;
BEGIN
    -- tenta ler variáveis de sessão da aplicação
    BEGIN
        v_usuario_id := nullif(current_setting('app.user_id', true), '')::bigint;
    EXCEPTION WHEN OTHERS THEN
        v_usuario_id := NULL;
    END;

    BEGIN
        v_ip := nullif(current_setting('app.ip', true), '');
    EXCEPTION WHEN OTHERS THEN
        v_ip := NULL;
    END;

    IF TG_OP = 'INSERT' THEN
        v_detalhes := 'new=' || to_jsonb(NEW)::text;
        INSERT INTO auditoria_logs (data_hora, usuario_id, acao, recurso, ip, detalhes)
        VALUES (now(), v_usuario_id, 'INSERT', v_recurso, v_ip, v_detalhes);
        RETURN NEW;

    ELSIF TG_OP = 'UPDATE' THEN
        v_detalhes := 'old=' || to_jsonb(OLD)::text || ' new=' || to_jsonb(NEW)::text;
        INSERT INTO auditoria_logs (data_hora, usuario_id, acao, recurso, ip, detalhes)
        VALUES (now(), v_usuario_id, 'UPDATE', v_recurso, v_ip, v_detalhes);
        RETURN NEW;

    ELSIF TG_OP = 'DELETE' THEN
        v_detalhes := 'old=' || to_jsonb(OLD)::text;
        INSERT INTO auditoria_logs (data_hora, usuario_id, acao, recurso, ip, detalhes)
        VALUES (now(), v_usuario_id, 'DELETE', v_recurso, v_ip, v_detalhes);
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- =========================================================
-- 2) Anexa triggers nas tabelas principais
-- =========================================================
DO $$
DECLARE
    t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'usuarios',
    'usuario_perfis',
    'cursos',
    'disciplinas',
    'turmas',
    'turmas_alunos',
    'turmas_professores',
    'formularios',
    'formularios_turmas',
    'questoes',
    'alternativas',
    'avaliacoes',
    'respostas'
  ]
  LOOP
    EXECUTE format($f$
      DROP TRIGGER IF EXISTS trg_audit_%1$s ON %1$s;
      CREATE TRIGGER trg_audit_%1$s
        AFTER INSERT OR UPDATE OR DELETE ON %1$s
        FOR EACH ROW EXECUTE FUNCTION audit_generic();
    $f$, t);
  END LOOP;
END$$;
